### ISSUE TITLE
Summon throwing listener error after recent update to hyper

### ISSUE THREAD

**Issue by n8stowell82** [soutar/hyperterm-summon#28]
a couple of days ago I saw a notification popup in hyper saying that some plugins where updated, and that I should restart hyper to enable the updates.  after restarting, I will regularly throughout the day see an error popup.  below is the contents of the error:

```
Uncaught Exception:
TypeError: "listener" argument must be a function
    at App.removeListener (events.js:326:15)
    at module.exports (/Users/nstowell/.hyper_plugins/node_modules/hyperterm-summon/modules/dispose.js:7:7)
    at Object.exports.onUnload.app [as onUnload] (/Users/nstowell/.hyper_plugins/node_modules/hyperterm-summon/index.js:13:27)
    at modules.forEach.mod (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:121:11)
    at Array.forEach (native)
    at clearCache (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:119:11)
    at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:72:7)
    at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:42:7)
    at cp.execFile.err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:27:13)
    at ChildProcess.exithandler (child_process.js:209:7)
```

**Comment by dcalhoun** [comment]
What version of hyperterm-summon do you currently have installed?

I published an update this morning that hopefully resolves your issue. If not, please post back with any additional information you might have about reproducing the error (e.g. what we’re you doing before and during the error occurrence).

**Comment by n8stowell82** [comment]
Thank you @dcalhoun .  I was running 2.0.1. I tried using the "update" action under the "plugins" menu item and that would cause the error.  Unable to update the plugin through the "wizard" I had to use hpm to uninstall and reinstall summon.  the summon package.json now shows 2.0.2, but trying to run the "update" action from the "plugin" menu still throws the error:

```
Uncaught Exception:
TypeError: "listener" argument must be a function
    at App.removeListener (events.js:326:15)
    at module.exports (/Users/nstowell/.hyper_plugins/node_modules/hyperterm-summon/modules/dispose.js:7:7)
    at Object.exports.onUnload.app [as onUnload] (/Users/nstowell/.hyper_plugins/node_modules/hyperterm-summon/index.js:13:27)
    at modules.forEach.mod (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:121:11)
    at Array.forEach (native)
    at clearCache (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:119:11)
    at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:72:7)
    at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:42:7)
    at cp.execFile.err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:27:13)
    at ChildProcess.exithandler (child_process.js:209:7)
```

**Comment by n8stowell82** [comment]
ah seems like hard restarting hyper vs jut reloading the page, seems to have done the trick.  Running the update command works with no error.  I have noticed that I would see the error when waking the computer up from sleep, so I will keep an eye out for that and report back if I notice it again. I am going to close this issue as it seems good now.  Thanks for your help!!!

**Comment by dcalhoun** [comment]
Hit another one this evening, so definitely an ongoing issue. It appears tied to [these lines](https://github.com/zeit/hyper/blob/2.0.4/app/plugins.js#L109-L113).

```
Uncaught Exception:
TypeError: cfgUnsubscribe is not a function
    at module.exports (/Users/username/.hyper_plugins/node_modules/hyperterm-summon/modules/dispose.js:11:3)
    at Object.exports.onUnload.app [as onUnload] (/Users/username/.hyper_plugins/node_modules/hyperterm-summon/index.js:14:27)
    at modules.forEach.mod (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:111:11)
    at Array.forEach (native)
    at clearCache (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:109:11)
    at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:70:7)
    at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:47:7)
    at cp.execFile.err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:32:15)
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
```

**Comment by n8stowell82** [comment]
I was just about to post the same. It just hit me as well.  exact same issue.  I was not interacting with hyper at all when it popped

**Comment by dcalhoun** [comment]
@n8stowell82 published a fix. Hopefully the errors cease to show up. Let me know if you experience otherwise.

**Comment by n8stowell82** [comment]
@dcalhoun just updated to the new version.  There were a few errors during the update process, but it seemed to finally work (had to do complete uninstall/reinstall).  I will post here if I see any more issues.  Thank you for your help!
